### ISSUE TITLE
Getting a segmentation fault in node

### ISSUE THREAD

**Issue by parikh20** [Dynamsoft/barcode-reader-javascript#121]
I'm getting this error when attempting to run code simple to the sample code for the node.js module.
`/c/Program Files/nodejs/npm: line 44:   614 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"
`

Here's my code
``` 
async decode() {
    let reader;
    try {
      reader = await dbr.BarcodeReader.createInstance();
    } catch (err) {
      return err;
    }

    let results;
    try {
      results = await reader.decode('../test_id/id_back.jpg');
      for(let result of results){
        console.log(result.barcodeText);
      }
    } catch (err) {
      return err
    }

    reader.destroy();
}

**Comment by Keillion** [comment]
Hi, Jaineek

Sorry for the late reply.

What the version you use? We recommend to use https://www.npmjs.com/package/dynamsoft-node-barcode for node.

Can you show us the image causing the `Segmentation fault`?

**Comment by coheedandcambria** [comment]
No response, so this issue will be closed.
