### ISSUE TITLE
Any flash control?

### ISSUE THREAD

**Issue by moz-ljp** [Dynamsoft/barcode-reader-javascript#128]
Hi, implementing this into an webapp at the moment but theres a chance it might be used in low light conditions. Do you guys have any way built-in to enable the flashlight of a mobile device?

Cheers

**Comment by Keillion** [comment]
I think you have found the answer. Note that only android supports [turnOnTorch()](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/api-reference/BarcodeScanner.html?ver=9.6.10#turnontorch). Safari doesn't provide an API to control flashlight.
